validation_reports:
  max_reports_before_archive: 2  # Maximum number of reports before triggering archival
  reports_dir: "docs/validation_reports"  # Directory containing the reports
  index_file: "docs/validation_reports/index.json"  # Mapping file for redirections

zenodo:
  metadata_template:
    upload_type: "dataset"
    access_right: "open"
    license: "CC0-1.0"
    creators:
      - name: "OpenCitations Bot"
        affiliation: "OpenCitations"
    version: "1.0.0"
    keywords: 
      - "OpenCitations"
      - "validation"
      - "reports"
      - "crowdsourcing"
    related_identifiers:
      - identifier: "https://github.com/opencitations/crowdsourcing"
        relation: "isSupplementTo"
        resource_type: "software" 