name: Archive validation reports
on:
  workflow_run:
    workflows: ["Issues manager"]
    types:
      - completed

jobs:
  Archive:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Add write permission to commit and push
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ZENODO_PRODUCTION: ${{ secrets.ZENODO_PRODUCTION }}
      ZENODO_SANDBOX: ${{ secrets.ZENODO_SANDBOX }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT || 'development' }}
    steps:
      - name: List files in the repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install --no-interaction --only main
        
      - name: Check and archive reports
        run: poetry run python3 crowdsourcing/archive_reports.py

      # Update index.json after archival
      - name: Commit changes
        if: always()  # Run even if previous steps fail
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/validation_reports/index.json
          git commit -m "chore: update validation reports index" || echo "No changes to commit"
          git push || echo "No changes to push" 