name: Issues manager
on:
  issues:
    types: [opened, edited]

# Ensure only one issue is processed at a time
concurrency: 
  group: issue-processing
  cancel-in-progress: false

jobs:
  Process:
    # Run only when the issue has the 'deposit' label
    if: contains(github.event.issue.labels.*.name, 'deposit')
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Add write permission to commit and push
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      ZENODO_PRODUCTION: ${{ secrets.ZENODO_PRODUCTION }}
      ZENODO_SANDBOX: ${{ secrets.ZENODO_SANDBOX }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT || 'development' }}
    steps:
      - name: List files in the repository
        uses: actions/checkout@v4
      
      - name: Configure Git
        run: |
          git config --global user.name "crocibot"
          git config --global user.email "contact@opencitations.net"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: poetry install --no-interaction --only main
        
      - name: Process and validate the issue
        id: process
        run: poetry run python3 crowdsourcing/process_issues.py

      - name: Check for changes
        id: check_changes
        run: |
          git add docs/validation_reports/
          if ! git diff --cached --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit validation changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git pull --rebase origin main
          git commit -m "chore: update validation reports [skip ci]"
          git push

      - name: Archive reports
        if: steps.check_changes.outputs.has_changes == 'true'
        run: poetry run python3 crowdsourcing/archive_reports.py

      - name: Commit archive changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add docs/validation_reports/
          git pull --rebase origin main
          git commit -m "chore: archive validation reports"
          git push
